In [7]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

array = [1, (-2), 0.5];
print(softmax(array))

[0.6037489  0.03005889 0.36619222]


### Classifier Metrics Calculator

In [8]:
import numpy as np

def classifier_metrics(input_array,total_examples):
    true_positives=input_array[0,0];
    false_positives=input_array[0,1];

    false_negatives=input_array[1,0];
    true_negatives=input_array[1,1];
    
    accuracy =(true_positives + true_negatives) / (total_examples)
    precision = (true_positives) / (true_positives + false_positives)
    recall = (true_positives) / (true_positives + false_negatives)
    F1_score = (2 * precision * recall) / (precision + recall)
    
    print("accuracy = ", accuracy,"\n",
          "precision = ",precision,"\n",
          "recall = ", recall,'\n',
         "F1_score = ",F1_score)
    return [accuracy,precision,recall,F1_score]
    
input_array=np.array([[85,890],[15,10]]);
total_examples = 1000

In [9]:
classifier_metrics(input_array,total_examples)

accuracy =  0.095 
 precision =  0.08717948717948718 
 recall =  0.85 
 F1_score =  0.1581395348837209


[0.095, 0.08717948717948718, 0.85, 0.1581395348837209]

In [10]:
from sympy import symbols, diff
import sympy as sp

x, y = symbols('x y',real=True)

f=sp.sin(x*y)*sp.exp(x)

diff(f,x)

y*exp(x)*cos(x*y) + exp(x)*sin(x*y)

In [11]:
>> from sympy import symbols, diff
>>> x, y, z = symbols('x y z', real=True)
>>> f = 4*x*y + x*sin(z) + x**3 + z**8*y
>>> diff(f, x)
4*y + sin(z) + 3*x**2

SyntaxError: invalid syntax (<ipython-input-11-9972238e1f6c>, line 1)

In [12]:
import numpy as np
import pandas as pd

In [25]:
X = np.array([[1,2],[2,1]])
pd.DataFrame(X)

0  1
0  1  2
1  2  1

In [26]:
Xsqr=np.dot(X,X)
pd.DataFrame(Xsqr)

0  1
0  5  4
1  4  5

$ X = $

In [1]:
import tensorflow as tf

g = tf.Graph()

with g.as_default():
    a = tf.placeholder(tf.float32, name="a")
    b = tf.placeholder(tf.float32, name="b")
    c = a + b

/Users/John_T_Leonard/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
[node.name for node in g.as_graph_def().node]

['a', 'b', 'add']

In [3]:
g.as_graph_def().node[2].input

['a', 'b']

In [6]:
# We write the graph out to the `logs` directory
tf.summary.FileWriter("logs", g).close()

In [6]:
import numpy as np
A = np.random.randn(4,3)
print(A)
B = np.sum(A, axis = 1, keepdims = True)
print(B)
B.shape

[[-1.53386873  0.09845177  3.49757486]
 [ 1.77876117  0.37820737 -0.98237725]
 [-0.54941994 -1.14927445  0.22715656]
 [-1.64344831  0.43781009 -0.18891292]]
[[ 2.0621579 ]
 [ 1.1745913 ]
 [-1.47153783]
 [-1.39455114]]


(4, 1)